window.INNIOASIS_FIRMWARE_CATALOG = [
    { slug: "original-y1", name: "Original Software", model: "Y1", repo: "y1-community/y1-stock-rom", packageName: "rom.zip", guide: "guides/restore-original-y1.html", seoPage: "original-software-y1.html", description: "The stock Software path for restoring an Innioasis Y1." },
    { slug: "original-y2", name: "Original Software", model: "Y2", repo: "y1-community/y1-stock-rom", packageName: "rom_y2.zip", guide: "guides/restore-original-y2.html", seoPage: "original-software-y2.html", description: "The stock Software path for restoring an Innioasis Y2." },
    { slug: "rockbox-y1", name: "Rockbox", model: "Y1", repo: "rockbox-y1/rockbox", packageName: "rom.zip", guide: "guides/rockbox-y1.html", seoPage: "rockbox-y1-software.html", description: "A music-first custom Software with deep playback and theme options." },
    { slug: "rockbox-y2", name: "Rockbox", model: "Y2", repo: "y1-community/rockbox-y2-rom", packageName: "rom_y2.zip", guide: "guides/rockbox-y2.html", seoPage: "rockbox-y2-software.html", description: "The Y2 Rockbox build. Select Y2 before choosing this Software." },
    { slug: "solar-y1", name: "Solar", model: "Y1", repo: "thesolarproject/solar", packageName: "rom.zip", guide: "guides/solar-y1.html", seoPage: "solar-y1-software.html", description: "A Y1 custom Software with network features, including YouTube support." },
    { slug: "solar-y2", name: "Solar", model: "Y2", repo: "thesolarproject/solar", packageName: "rom_y2.zip", guide: "guides/solar-y2.html", seoPage: "solar-y2-software.html", description: "Listed for Y2 in the current Updater catalogue. Check release notes before installing." },
    { slug: "jj-launcher-y1", name: "JJ Launcher", model: "Y1", repo: "ismileblue/y1_launcher", packageName: "rom.zip", guide: "guides/jj-launcher-y1.html", seoPage: "jj-launcher-y1-software.html", description: "A launcher Software for Y1." },
    { slug: "jj-launcher-y2", name: "JJ Launcher", model: "Y2", repo: "ismileblue/y1_launcher", packageName: "rom_y2.zip", guide: "guides/jj-launcher-y2.html", seoPage: "jj-launcher-y2-software.html", description: "Listed for Y2 in the current Updater catalogue. Check release notes before installing." },
    { slug: "inniclassic-y1", name: "Inniclassic", model: "Y1", repo: "FabianZettl/inniclassic", packageName: "rom.zip", guide: "guides/inniclassic-y1.html", seoPage: "inniclassic-y1-software.html", description: "A classic-style Y1 Software." },
    { slug: "y2player-y2", name: "Y2Player", model: "Y2", repo: "schulzcode/Y2Player", packageName: "rom_y2.zip", guide: "guides/y2player-y2.html", seoPage: "y2player-y2-software.html", description: "A Y2 custom Software." },
    { slug: "koensayr-y1", name: "Koensayr", model: "Y1", repo: "ryan-specter/koensayr-auto", packageName: "rom.zip", guide: "guides/koensayr-y1.html", seoPage: "koensayr-y1-software.html", description: "A Y1 custom Software maintained by the community." }
];
